version: '3'
services:
  api-service:
    image: node:16
    container_name: auth_api
    volumes:
      - ./node_modules:/node_modules
      - ./api:/api
      - ./shared:/shared
      - ./tscofing.json:/tscofing.json
      - .package.json:/package.json
    ports: 
      - '3001:3001'
    working_dir: /
    command: yarn run ts-node-dev --project api/tsconfig.json -r tsconfig-paths/register api/index.ts
    env_file: .env.development

  mongodb:
    image: mongo:5
    container_name: auth_mongodb
    ports:
      - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: bandity
      MONGO_INITDB_ROOT_PASSWORD: 1234f